spring.application.name=CozyHeven

#AWS SETTINGS
#spring.datasource.url=jdbc:mysql://cozy-heven-db.c18m8yiomdh0.ap-south-1.rds.amazonaws.com/trs-db?createDatabaseIfNotExist=true
#spring.datasource.username=admin
#spring.datasource.password=Thanika2005
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# H2 DB Settings
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.url=jdbc:mysql://localhost:3306/cozy_heven_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Thanika@2005

logging.level.org.springframework.security=DEBUG


#Hibernate Settings
spring.jpa.hibernate.ddl-auto=update

#Security props
jwt.secret=secret